version: '3.8'

services:
  app:
    build:
        context: .
        dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
        - ./:/var/www
    networks:
        - pokedex_network

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8989:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - pokedex_network

  db:
    image: mysql:8.0
    container_name: pokedex_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - pokedex_network

volumes:
  mysql_data:
    driver: local

networks:
  pokedex_network:
    driver: bridge
